name: 'Reaction Comments'
description: 'Delete +1 comments and encourage the use of GitHub reactions'
author: 'Armin Sebastian'
inputs:
  github-token:
    description: 'GitHub access token'
    default: '${{ github.token }}'
  exempt-issue-labels:
    description: 'Do not process comments on issues with these labels, value must be a comma separated list of labels'
    default: ''
  issue-comment:
    description: 'Replace matching comments on issues with this message, `{comment-author}` is an optional placeholder'
    default: >
      :wave: @{comment-author}, would you like to leave
      a reaction instead?
  exempt-pr-labels:
    description: 'Do not process comments on pull requests with these labels, value must be a comma separated list of labels'
    default: ''
  pr-comment:
    description: 'Replace matching comments on pull requests with this message, `{comment-author}` is an optional placeholder'
    default: >
      :wave: @{comment-author}, would you like to leave
      a reaction instead?
  process-only:
    description: 'Process comments only on issues or pull requests, value must be either `issues` or `prs`'
    default: ''
  log-output:
    description: 'Log output parameters, value must be either `true` or `false`'
    default: false
outputs:
  comments:
    description: 'Comments that have been either deleted or scheduled for removal, value is a JSON string'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'message-square'
  color: 'green'
